"""Inject build timestamp into src/build_info.h before each compile."""
import os
from datetime import datetime

Import("env")

INFO = os.path.join(env["PROJECT_DIR"], "src", "build_info.h")
TS = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
VER = env.GetProjectOption("custom_version", "0.1.0")

contents = (
    "// Auto-generated by scripts/pre_build.py - do not edit by hand.\n"
    "#pragma once\n\n"
    '#define ON3PORK_VERSION "{ver}"\n'
    '#define ON3PORK_NAME    "0N3P0rK"\n'
    '#define ON3PORK_BUILD   "{ts}"\n'
).format(ver=VER, ts=TS)

with open(INFO, "w", encoding="ascii") as f:
    f.write(contents)

print("[pre_build] wrote {p} (v={v} build={t})".format(p=INFO, v=VER, t=TS))
